name: Deb Reverse Analysis

on:
  workflow_dispatch:
    inputs:
      deb_file:
        description: 'Path or URL to .deb file'
        required: true
        default: 'deb/1.deb'

permissions:
  contents: write  # 允许提交回仓库

jobs:
  analyze-deb:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 保留写入令牌，便于后续 push

      - name: Set up Homebrew with caching and USTC mirrors
        uses: Homebrew/actions/setup-homebrew@master
        with:
          cache: true
        run: |
          # 配置中科大镜像源
          echo 'export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"' >> ~/.zshrc
          echo 'export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"' >> ~/.zshrc
          echo 'export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"' >> ~/.zshrc
          echo 'export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"' >> ~/.zshrc
          source ~/.zshrc

      - name: Install dependencies
        run: |
          brew update
          brew install dpkg python3
          pip3 install lief

      - name: Run full analysis pipeline
        run: |
          bash scripts/run_all.sh "${{ github.event.inputs.deb_file }}"

      - name: Upload raw analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raw-results
          path: output/raw  # 上传 output/raw 目录作为工件

      - name: Upload generated source artifacts
        uses: actions/upload-artifact@v4
        with:
          name: src-results
          path: output/src  # 上传 output/src 目录作为工件

      - name: Commit generated outputs back to repo
        run: |
          # 配置 git 用户信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 将新增/修改的 output 目录纳入版本控制
          git add output/raw output/src
          # 仅当有改动时才提交
          if ! git diff --cached --quiet; then
            git commit -m "chore: add reverse-analysis outputs [ci skip]"
            git push
          else
            echo "No changes to commit"
          fi
