name: Advanced Deb Reverse Analysis 

on:
  workflow_dispatch:
    inputs:
      deb_file:
        description: 'Path to .deb file'
        required: true

permissions:
  contents: write

jobs:
  analyze-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils xz-utils python3 python3-pip llvm clang file
        pip3 install lief

    - name: Setup directories
      run: |
        mkdir -p work/{control,data}
        mkdir -p output/{raw,src}

    - name: Extract .deb file
      run: |
        find . -name "*.deb" -exec cp {} work/ \;
        cd work
        ar x *.deb
        tar -xf control.tar.* -C control
        tar -xf data.tar.* -C data

    - name: Process dylib (Mach-O compatible)
      run: |
        DYMLIB_PATH=$(find work/data -name "*.dylib" -print -quit)
        if [ -f "$DYMLIB_PATH" ]; then
          echo "Found dylib: $DYMLIB_PATH"
          mkdir -p output/raw
          cp "$DYMLIB_PATH" output/raw/WechatPushMsgPage.dylib
          
          # 使用file命令验证文件类型
          file "$DYMLIB_PATH" > output/raw/file_info.txt
          
          # 使用LLVM工具链分析
          llvm-nm --demangle "$DYMLIB_PATH" > output/raw/nm_output.txt 2>&1 || echo "llvm-nm failed, using fallback methods..."
          
          # Python 脚本替代 lief-export
          python3 scripts/lief_analysis.py \
            --dylib "$DYMLIB_PATH" \
            --output output/raw/lief_export.txt

          strings "$DYMLIB_PATH" | grep -E 'OBJC_CLASS|_TTS|_OBJC_' > output/raw/objc_symbols.txt
        else
          echo "::error::No .dylib found in package!"
          exit 1
        fi

    - name: Run analysis scripts
      run: |
        python3 scripts/generate_headers.py \
          --dylib output/raw/WechatPushMsgPage.dylib \
          --symbols output/raw/objc_symbols.txt \
          --output output/src
        
        python3 scripts/generate_tweak_xm.py \
          --strings output/raw/objc_symbols.txt \
          --output output/src
        
        python3 scripts/generate_makefile.py \
          --name WechatPushMsgPage \
          --output output/src

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: reverse-analysis-results
        path: |
          output/raw/
          output/src/

    - name: Commit reverse analysis output to repository
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add output/raw output/src
        git commit -m "Add reverse-analysis output: raw + src" || echo "No changes to commit"
        git push
