name: Advanced Deb Reverse Analysis

on:
  workflow_dispatch:
    inputs:
      deb_file:
        description: 'Path to .deb file'
        required: true

permissions:
  contents: write

jobs:
  analyze-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils xz-utils python3 python3-pip llvm clang file
        pip3 install lief

    - name: Setup directories
      run: |
        mkdir -p work/{control,data}
        mkdir -p output/{raw,src}

    - name: Download .deb file
      run: |
        wget https://github.com/axs66/nxfx/blob/main/deb/1.deb -O work/1.deb

    - name: Extract .deb file
      run: |
        cd work
        ar x com.Axs.wechat-push-msg-page_0.0.3_iphoneos-arm64.deb
        tar -xf control.tar.* -C control
        tar -xf data.tar.* -C data

    - name: Process dylib (Mach-O compatible)
      run: |
        DYMLIB_PATH=$(find work/data -name "*.dylib" -print -quit)
        if [ -f "$DYMLIB_PATH" ]; then
          echo "Found dylib: $DYMLIB_PATH"
          mkdir -p output/raw
          cp "$DYMLIB_PATH" output/raw/WechatPushMsgPage.dylib
          
          # 使用file命令验证文件类型
          file "$DYMLIB_PATH" > output/raw/file_info.txt
          
          # 使用LLVM工具链分析符号
          llvm-nm --demangle "$DYMLIB_PATH" > output/raw/nm_output.txt 2>&1 || echo "llvm-nm failed"

          # 用 lief 分析 Mach-O 结构
          python3 scripts/lief_analysis.py \
            --dylib "$DYMLIB_PATH" \
            --output output/raw/lief_export.txt

          # 简单 grep 出 objc/Swift 字符串
          strings "$DYMLIB_PATH" | grep -E 'OBJC_CLASS|_TTS|_OBJC_' > output/raw/objc_symbols.txt
        else
          echo "::error::No .dylib found in package!"
          exit 1
        fi

    - name: Run final reverse pipeline (headers, tweak, Makefile)
      run: |
        DEB_PATH="work/com.Axs.wechat-push-msg-page_0.0.3_iphoneos-arm64.deb"
        bash scripts/run_all.sh "$DEB_PATH"

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: reverse-analysis-results
        path: |
          output/raw/
          output/src/
