name: Deb Reverse Analysis

on:
  workflow_dispatch:
    inputs:
      deb_file:
        description: 'Path or URL to .deb file'
        required: true
        default: 'deb/1.deb'

permissions:
  contents: write

jobs:
  analyze-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils dpkg-dev xz-utils python3 python3-pip llvm clang file dpkg frida-tools
          pip3 install lief

      - name: Run full analysis pipeline
        run: |
          bash scripts/run_all.sh "${{ github.event.inputs.deb_file }}"

      - name: Upload raw analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raw-results
          path: output/raw

      - name: Upload generated source artifacts
        uses: actions/upload-artifact@v4
        with:
          name: src-results
          path: output/src

      - name: Commit generated outputs back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/raw output/src
          if ! git diff --cached --quiet; then
            git commit -m "chore: add reverse-analysis outputs [ci skip]"
            git push
          else
            echo "No changes to commit"
