name: CI

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - '**.xm'
      - 'control'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Theos
        uses: axs66/theos-action@main

      - name: Export variables (skip SDK requirement)
        run: echo "THEOS_PACKAGE_SCHEME=rootless" >> $GITHUB_ENV

      - name: Clean packages
        run: rm -f ${{ github.workspace }}/packages/*.deb

      - name: Build
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 抖音净化
          path: ${{ github.workspace }}/packages/*.deb
