name: deb reverse analysis

on:
  workflow_dispatch:

jobs:
  analyze-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils xz-utils

    - name: Extract .deb file
      run: |
        mkdir -p work
        cp input/*.deb work/
        cd work
        ar x *.deb
        mkdir -p control data
        tar -xf control.tar.* -C control
        tar -xf data.tar.* -C data

    - name: Prepare output folders
      run: |
        mkdir -p output/control
        mkdir -p output/data
        mkdir -p output/raw

    - name: Copy extracted files
      run: |
        cp -r work/control/* output/control/ || true
        cp -r work/data/* output/data/ || true

    - name: Upload raw .dylib for local analysis
      run: |
        dylib=$(find work/data -name "*.dylib" | head -n 1)
        if [ -f "$dylib" ]; then
          echo "Found dylib: $dylib"
          cp "$dylib" output/raw/WechatPushMsgPage.dylib
          echo "Symbol extraction skipped (Mach-O ARM64 not supported on Linux)." > output/symbols.txt
        else
          echo "No .dylib file found!" > output/symbols.txt
        fi

    - name: Commit and push results using PAT
      env:
        TOKEN: ${{ secrets.PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add output/
        git commit -m "Auto extract and analyze deb content" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
